# Generated by Django 5.2.14 on 2026-05-05 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('imap_host', models.CharField(default='imap.mail.ru', max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('encrypted_password', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('email_address',),
                'unique_together': {('owner', 'email_address')},
            },
        ),
    ]
