# Generated by Django 5.2.14 on 2026-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
