# Generated by Django 5.2.14 on 2026-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='group',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
