# Generated by Django 5.2.14 on 2026-05-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailaccount_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='account_limit_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
