# Generated by Django 5.2.15 on 2026-06-03 19:16

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_api_tokens_and_user_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.emailaccount')),
            ],
            options={
                'verbose_name_plural': 'email aliases',
                'ordering': ('email_address',),
            },
        ),
        migrations.AddConstraint(
            model_name='emailalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email_address'), models.F('account'), name='unique_alias_address_per_account_ci'),
        ),
    ]
